# Generated by Django 5.0.3 on 2024-04-02 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("postal_cod", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("google_maps_url", models.URLField()),
                ("google_maps_iframe", models.CharField(max_length=512)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nif", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modified_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("token", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FavouriteParkings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ParkOnLive.parking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingOccupancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupancy_current", models.IntegerField()),
                ("occupancy_max", models.IntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ParkOnLive.parking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parking",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ParkOnLive.provider"
            ),
        ),
    ]
